### ISSUE TITLE
`get_synchronization_result` is not implemented in `GrpcServerModelProxy`

### ISSUE THREAD

**Issue by MohammedAljahdali** [sands-lab/splitbud#1]
The `get_synchronization_result` in the `ServerModelProxy` is not implemented in `GrpcServerModelProxy`.

**Comment by BorisRado** [comment]
it's not supposed to be implemented in `GrpcServerModelProxy` because the user is not supposed to directly call the `_get_synchronization_result` method.
There is actually a problem in the design, as now, there is a single server proxy class, which is used both for internals and for exposure to the client:
-  `get_parameters`, `_get_synchronization_result`, `configure_fit`, `configure_evaluate`, `_update_server_model_requests`: are used internally to communicate with the server model. The user should **not** invoke such methods at any time.
- All the other methods can be invoked by the user.

Simple (and temporary) solution is to add an underscore to all the methods that are used internally to explicitly show that the methods are for internals only (as it's done with `_get_synchronization_result`). However, ideally we should split this logic into two separate classes to avoid any confusion, i.e., having a server proxy class for internal functioning and another class with only the methods exposed to the user.
